package activities

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os/exec"
	"regexp"
	"strings"
	"time"
)

// Review status values returned by FetchReviewStatus.
const (
	ReviewApproved         = "approved"
	ReviewChangesRequested = "changes_requested"
	ReviewPending          = "pending" // no CodeRabbit verdict yet, or a non-blocking comment
)

type ReviewResult struct {
	Status   string
	Feedback string // CodeRabbit's review body; populated when Status == ReviewChangesRequested
}

// CreatePR opens a pull request for the task's branch via the gh CLI. It's
// idempotent: if a PR already exists for this branch (e.g. the workflow
// retried after a crash), it returns the existing PR number instead of
// creating a duplicate.
func CreatePR(ctx context.Context, task Task) (int, error) {
	root, err := RepoRoot()
	if err != nil {
		return 0, err
	}
	if num, ok, err := existingPR(ctx, task.Branch); err != nil {
		return 0, err
	} else if ok {
		return num, nil
	}

	cmd := exec.CommandContext(ctx, "gh", "pr", "create",
		"--head", task.Branch,
		"--base", "main",
		"--title", "Automated: "+task.ID,
		"--body", "Auto-generated by the Claude pipeline for `"+strings.TrimPrefix(task.Path, root+"/")+"`.",
	)
	cmd.Dir = root
	if out, err := cmd.CombinedOutput(); err != nil {
		return 0, fmt.Errorf("gh pr create failed: %w: %s", err, string(out))
	}

	num, ok, err := existingPR(ctx, task.Branch)
	if err != nil {
		return 0, err
	}
	if !ok {
		return 0, fmt.Errorf("gh pr create reported success but no PR found for branch %s", task.Branch)
	}
	return num, nil
}

func existingPR(ctx context.Context, branch string) (int, bool, error) {
	root, err := RepoRoot()
	if err != nil {
		return 0, false, err
	}
	cmd := exec.CommandContext(ctx, "gh", "pr", "view", branch, "--json", "number")
	cmd.Dir = root
	out, err := cmd.Output()
	if err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) && strings.Contains(string(exitErr.Stderr), "no pull requests found") {
			return 0, false, nil
		}
		return 0, false, fmt.Errorf("gh pr view %s: %w", branch, err)
	}

	var result struct {
		Number int `json:"number"`
	}
	if err := json.Unmarshal(out, &result); err != nil {
		return 0, false, fmt.Errorf("parsing pr number: %w", err)
	}
	return result.Number, true, nil
}

type ghReview struct {
	User struct {
		Login string `json:"login"`
	} `json:"user"`
	State       string    `json:"state"`
	Body        string    `json:"body"`
	CommitID    string    `json:"commit_id"`
	SubmittedAt time.Time `json:"submitted_at"`
}

// FetchReviewStatus inspects the PR's reviews and returns CodeRabbit's most
// recent verdict, distinguishing approved / changes-requested / no-verdict-yet
// by the review's actual `state` field rather than just checking whether any
// review text exists.
//
// Two pull_request_review webhook deliveries can land as back-to-back signals
// (GitHub sometimes sends more than one for what's logically the same event),
// and the second Receive() fires before CodeRabbit has reviewed the commit the
// first round just pushed. Without the commit_id check below, that replays
// the same already-fixed feedback through AddressFeedback a second time. So
// a review only counts if it was submitted against the PR's *current* head
// commit; anything reviewing an older commit is stale and treated as pending.
func FetchReviewStatus(ctx context.Context, prNumber int) (ReviewResult, error) {
	root, err := RepoRoot()
	if err != nil {
		return ReviewResult{}, err
	}

	headCmd := exec.CommandContext(ctx, "gh", "pr", "view", fmt.Sprintf("%d", prNumber), "--json", "headRefOid")
	headCmd.Dir = root
	headOut, err := headCmd.Output()
	if err != nil {
		return ReviewResult{}, fmt.Errorf("gh pr view headRefOid: %w", err)
	}
	var head struct {
		HeadRefOid string `json:"headRefOid"`
	}
	if err := json.Unmarshal(headOut, &head); err != nil {
		return ReviewResult{}, fmt.Errorf("parsing head ref: %w", err)
	}

	cmd := exec.CommandContext(ctx, "gh", "api", "--paginate", fmt.Sprintf("repos/{owner}/{repo}/pulls/%d/reviews", prNumber))
	cmd.Dir = root
	out, err := cmd.Output()
	if err != nil {
		return ReviewResult{}, fmt.Errorf("gh api pulls reviews: %w", err)
	}

	var reviews []ghReview
	if err := json.Unmarshal(out, &reviews); err != nil {
		return ReviewResult{}, fmt.Errorf("parsing reviews: %w", err)
	}

	// Only APPROVED/CHANGES_REQUESTED carry an actual verdict. CodeRabbit
	// also posts plain COMMENTED reviews (status updates, walkthroughs)
	// that don't supersede the prior verdict, so they're skipped here
	// rather than masking a still-outstanding CHANGES_REQUESTED as pending.
	var latest *ghReview
	for i := range reviews {
		r := &reviews[i]
		if r.User.Login != "coderabbitai[bot]" {
			continue
		}
		if r.State != "APPROVED" && r.State != "CHANGES_REQUESTED" {
			continue
		}
		if latest == nil || r.SubmittedAt.After(latest.SubmittedAt) {
			latest = r
		}
	}

	if latest == nil || latest.CommitID != head.HeadRefOid {
		return ReviewResult{Status: ReviewPending}, nil
	}
	switch latest.State {
	case "APPROVED":
		return ReviewResult{Status: ReviewApproved}, nil
	default: // CHANGES_REQUESTED
		return ReviewResult{Status: ReviewChangesRequested, Feedback: latest.Body}, nil
	}
}

type ChecksResult struct {
	AllPassed bool
	Failures  string // failing check names/links plus a tail of their logs, for feeding back to Claude
}

var runIDPattern = regexp.MustCompile(`/actions/runs/(\d+)`)

// WaitForChecks polls the PR's CI checks (gh pr checks) until none are left
// pending, then reports whether everything passed. CodeRabbit's own approval
// isn't sufficient to merge: PR #8 was merged with a failing frontend build
// because nothing checked actual CI status before calling MergePR.
func WaitForChecks(ctx context.Context, prNumber int) (ChecksResult, error) {
	root, err := RepoRoot()
	if err != nil {
		return ChecksResult{}, err
	}

	type ghCheck struct {
		Name   string `json:"name"`
		Bucket string `json:"bucket"`
		Link   string `json:"link"`
	}

	var checks []ghCheck
	for {
		cmd := exec.CommandContext(ctx, "gh", "pr", "checks", fmt.Sprintf("%d", prNumber),
			"--json", "name,bucket,link")
		cmd.Dir = root
		out, err := cmd.Output() // a non-zero exit just means a check failed/is pending; stdout still has the JSON
		if len(out) == 0 {
			return ChecksResult{}, fmt.Errorf("gh pr checks: %w", err)
		}
		if err := json.Unmarshal(out, &checks); err != nil {
			return ChecksResult{}, fmt.Errorf("parsing pr checks: %w", err)
		}

		pending := false
		for _, c := range checks {
			if c.Bucket == "pending" {
				pending = true
				break
			}
		}
		if !pending {
			break
		}
		select {
		case <-ctx.Done():
			return ChecksResult{}, ctx.Err()
		case <-time.After(10 * time.Second):
		}
	}

	var sb strings.Builder
	for _, c := range checks {
		if c.Bucket != "fail" && c.Bucket != "cancel" {
			continue
		}
		sb.WriteString(fmt.Sprintf("- %s (%s): %s\n", c.Name, c.Bucket, c.Link))
		if m := runIDPattern.FindStringSubmatch(c.Link); len(m) == 2 {
			logCmd := exec.CommandContext(ctx, "gh", "run", "view", m[1], "--log-failed")
			logCmd.Dir = root
			logOut, _ := logCmd.Output()
			sb.WriteString(fmt.Sprintf("\n--- %s failure log (tail) ---\n%s\n\n", c.Name, tailString(string(logOut), 4000)))
		}
	}

	if sb.Len() == 0 {
		return ChecksResult{AllPassed: true}, nil
	}
	return ChecksResult{AllPassed: false, Failures: "The following CI checks failed:\n" + sb.String()}, nil
}

func tailString(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[len(s)-maxLen:]
}

// MergePR merges the PR once it's approved. Squash matches this repo's
// actual convention (confirmed via merged PR history: "<title> (#N)" commits
// and squashMergeAllowed=true on the repo).
func MergePR(ctx context.Context, prNumber int) error {
	root, err := RepoRoot()
	if err != nil {
		return err
	}
	cmd := exec.CommandContext(ctx, "gh", "pr", "merge", fmt.Sprintf("%d", prNumber),
		"--squash", "--delete-branch")
	cmd.Dir = root
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("gh pr merge failed: %w: %s", err, string(out))
	}
	return nil
}
